name: Check

on:
  push:
  workflow_call:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]
        airflow-version: ["2.9.0", "2.10.5", "3.2.2"]
    name: Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libxmlsec1 libxmlsec1-dev python3-venv curl

          python -m pip install --upgrade pip

          CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${{ matrix.airflow-version }}/constraints-${{ matrix.python-version }}.txt"
          curl -sS "${CONSTRAINT_URL}" > constraints.txt

          sed -i '/^decorator==/d' constraints.txt
          sed -i '/^tqdm==/d' constraints.txt
          sed -i '/^ruff==/d' constraints.txt
          sed -i '/^mypy==/d' constraints.txt
          sed -i '/^pytest==/d' constraints.txt

          pip install apache-airflow==${{ matrix.airflow-version }} -c constraints.txt
          pip install -r dev/requirements.txt -c constraints.txt
          pip install kubernetes

      - name: Style check
        run: |
          ruff check
          ruff format --check

      - name: Type check
        run: |
          mypy

      - name: Pytest
        run: |
          if [[ "${{ matrix.airflow-version }}" == 2.* ]]; then
            airflow db init
          else
            airflow db migrate
          fi
          pytest --junitxml=report.xml

      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Pytest (${{ matrix.python-version }}, airflow ${{ matrix.airflow-version }})
          path: report.xml
          reporter: java-junit
